### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takahirohirayama** [takahirohirayama/furima-34430#9]
フリマアプリのURL　https://furima-34430.herokuapp.com/

Basic認証のIDとパスワード	admin/2222

出品者用のメールアドレス/パスワード	本番環境で使用可能なユーザーの情報
 test@mail.com   / test666666

購入者用のメールアドレスとパスワード	上記とは異なる、本番環境で使用可能なユーザーの情報
sample@mail.com / sample666666

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTMです✨**　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/49669977/112241312-59373600-8c8d-11eb-8df9-79a4d7d03772.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
